# Generated by Django 3.1.2 on 2020-11-24 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabelasDadosUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('sobreNome', models.CharField(blank=True, max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('senha', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, max_length=255)),
                ('pais', models.CharField(blank=True, max_length=255)),
                ('cep', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'db_table': 'dados_usuario',
            },
        ),
        migrations.CreateModel(
            name='tabelasDadosCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('sobreNome', models.CharField(blank=True, max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('endereco1', models.CharField(blank=True, max_length=50)),
                ('endereco2', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, max_length=255)),
                ('pais', models.CharField(blank=True, max_length=255)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('lembrarDados', models.CharField(blank=True, max_length=1)),
                ('modeloEstufa', models.CharField(blank=True, max_length=20)),
                ('tamanhoEstufa', models.CharField(blank=True, max_length=20)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginas.tabelasdadosusuario')),
            ],
            options={
                'db_table': 'dados_compra',
            },
        ),
    ]
