# Generated by Django 3.1.2 on 2020-11-27 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelasdadoscompra',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='tabelasdadoscompra',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='tabelasdadoscompra',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tabelasdadoscompra',
            name='endereco1',
        ),
        migrations.RemoveField(
            model_name='tabelasdadoscompra',
            name='endereco2',
        ),
        migrations.RemoveField(
            model_name='tabelasdadoscompra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tabelasdadoscompra',
            name='idUser',
        ),
        migrations.RemoveField(
            model_name='tabelasdadoscompra',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='tabelasdadoscompra',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='tabelasdadoscompra',
            name='sobreNome',
        ),
        migrations.RemoveField(
            model_name='tabelasdadosusuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tabelasdadosusuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='tabelasdadosusuario',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='tabelasdadosusuario',
            name='sobreNome',
        ),
        migrations.AddField(
            model_name='tabelasdadoscompra',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tabelasdadosusuario',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tabelasdadoscompra',
            name='lembrarDados',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='EnderecosDeEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('rua', models.CharField(blank=True, max_length=1)),
                ('casa', models.CharField(blank=True, max_length=10)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('bairro', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(blank=True, max_length=255)),
                ('pais', models.CharField(blank=True, max_length=255)),
                ('id_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dados_entrega',
            },
        ),
    ]
