# Generated by Django 3.1.2 on 2020-11-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_dadosestufa_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosestufa',
            name='bombaAgua',
        ),
        migrations.RemoveField(
            model_name='dadosestufa',
            name='estrutura',
        ),
        migrations.RemoveField(
            model_name='dadosestufa',
            name='fileiras',
        ),
        migrations.RemoveField(
            model_name='dadosestufa',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='dadosestufa',
            name='itensInclusos',
        ),
        migrations.RemoveField(
            model_name='dadosestufa',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='dadosestufa',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='dadosestufa',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='dadosestufa',
            name='tamanhoCM',
        ),
        migrations.RemoveField(
            model_name='dadosestufa',
            name='valor',
        ),
    ]
