# Generated by Django 3.1.2 on 2020-11-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_auto_20201130_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosEstufa',
        ),
    ]
