# Generated by Django 3.1.2 on 2020-11-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0011_dadosestufa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosEstufa',
        ),
    ]
