# Generated by Django 3.1.2 on 2020-12-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0013_dadosestufa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tabelasDadosCompra',
        ),
    ]
