# Generated by Django 3.1.2 on 2020-12-03 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas', '0014_delete_tabelasdadoscompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelasDadosCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCompra', models.DateField(auto_now=True)),
                ('lembrarDados', models.BooleanField()),
                ('id_entrega', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginas.enderecosdeentrega')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paginas.dadosestufa')),
                ('id_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dados_compra',
            },
        ),
    ]
