# Generated by Django 3.1.2 on 2020-12-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0015_tabelasdadoscompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecosdeentrega',
            name='rua',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
