# Generated by Django 3.1.2 on 2020-12-04 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas', '0016_auto_20201204_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecosdeentrega',
            name='id_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
            preserve_default=False,
        ),
    ]
